security:
  basic:
    enabled: true

management:
  security:
    enabled: true

logging:
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true # <----Change to true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
